version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    resource_class: xlarge
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/local/openjdk-17
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - v1-dependencies-
      
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
      
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test
      
      - run:
          name: Run Connected Tests
          command: |
            ./gradlew connectedDebugAndroidTest
      
      - store_test_results:
          path: app/build/test-results
      
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
