name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Enable KVM
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
        sudo adduser $USER libvirt
        sudo adduser $USER kvm

    - name: Install system image and create emulator
      run: |
        echo "y" | sdkmanager "system-images;android-30;google_apis;x86"
        echo "y" | sdkmanager "emulator"
        echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"
        $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-save -no-audio -no-window &
        adb wait-for-device
        adb shell settings put global window_animation_scale 0
        adb shell settings put global transition_animation_scale 0
        adb shell settings put global animator_duration_scale 0
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Run connected tests
      run: ./gradlew connectedDebugAndroidTest

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4.3.0
      with:
        name: test-results
        path: |
          app/build/test-results/
          app/build/reports/tests/
          app/build/outputs/androidTest-results/
          app/build/outputs/androidTest-results/connected/**
