name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Run connected tests
      run: ./gradlew connectedDebugAndroidTest

    - name: Upload test results
      if: always()
Missing download info for actions/setup-android@v3      uses: actions/upload-artifact@v4.3.0
      with:
        name: test-results
        path: |
          app/build/test-results/
          app/build/reports/tests/
          app/build/outputs/androidTest-results/
          app/build/outputs/androidTest-results/connected/**
